
default: png1 png2

png1:
	convert \
	 -verbose \
	 -density 300 \
	 -alpha off \
	 dark-page1.pdf \
	 dark-page1.png

png2:
	convert \
	 -verbose \
	 -density 300 \
	 -alpha off \
	 light-page1.pdf \
	 light-page1.png
